### ISSUE TITLE
How to display only fonts that have latin-ext support

### ISSUE THREAD

**Issue by vaclavgreif** [stylesplugin/styles-font-menu#7]
Is there a way ho display only fonts with latin-ext support?

**Comment by pdclark** [comment]
There's not currently a filter for this, but this is the line that's causing fonts to be limited to latin only: https://github.com/stylesplugin/styles-font-menu/blob/e8dab5b97cb76f744597e8f27cf378e8c6de524a/classes/sfm-group-google.php#L92

**Comment by vaclavgreif** [comment]
Works great, thanks!
