### ISSUE TITLE
Give the select a name

### ISSUE THREAD

**Issue by vaclavgreif** [stylesplugin/styles-font-menu#8]
How can I give a name to the `<select>`, to be able to get the value in my form submit?

**Comment by pdclark** [comment]
Updated the readme: [Field name, default value, and live preview](https://github.com/stylesplugin/styles-font-menu#field-name-default-value-and-live-preview)

**Comment by pdclark** [comment]
Just noticed that the live-update JavaScript was using the old name, `stylesFontDropdown`. I've updated it to `stylesFontMenu`.

If you use the last code you downloaded, the correct example would be:

``` js
(function($){

    // Elements we'd like to update
    var $headings = $( 'h2, h3' );

    // Attach to change event of all font menus
    // You might make this specific to one menu by selecting with an ID passed in attributes.
    // For example, $('#sfm-field-id').change( function(){
    $('select.sfm').change( function(){
        // When the menu changes, preview the font on elements identified above.
        $(this).data('stylesFontDropdown').preview_font_change( $headings );
    });

})(jQuery);
```

If you pull the latest version, then the readme will be correct. Only difference is `stylesFontDropdown` vs. `stylesFontMenu`.

**Comment by vaclavgreif** [comment]
Hmmm, when passing the `$attributes` array, the output is:

```
<select array="" class="sfm" data-selected="" data-placeholder="Select a Font..." style="display: none;">
```

It looks foreach or something is missing?
